### ISSUE TITLE
[ZooKeeperClient] Auth failed. (kafka.zookeeper.ZooKeeperClient)

### ISSUE THREAD

**Issue by jochen1234** [IBM/event-streams#24]
Hi,

i have installed ibm-eventstreams-prod 2018.3.1 with helm chart 1.1.0 on icp 3.1.2 Enterprise Edition. After running the helm chart the following pods are CrashLoopBackOff

[admin@localhost ~]$ kubectl get pods
NAME                                                             READY   STATUS             RESTARTS   AGE
test-instance-ibm-es-access-controller-deploy-7f5cc5f89b-nwp6h   2/2     Running            0          15h
test-instance-ibm-es-access-controller-deploy-7f5cc5f89b-xcf7k   2/2     Running            0          15h
test-instance-ibm-es-elastic-sts-0                               0/1     CrashLoopBackOff   177        15h
test-instance-ibm-es-elastic-sts-1                               0/1     CrashLoopBackOff   176        15h
test-instance-ibm-es-indexmgr-deploy-5ff44dfb9-bnbpb             1/1     Running            0          15h
test-instance-ibm-es-kafka-sts-0                                 3/4     CrashLoopBackOff   18         75m
test-instance-ibm-es-kafka-sts-1                                 3/4     CrashLoopBackOff   19         78m
test-instance-ibm-es-kafka-sts-2                                 3/4     CrashLoopBackOff   38         175m
test-instance-ibm-es-proxy-deploy-657bcbd7b-cclhp                1/1     Running            0          15h
test-instance-ibm-es-proxy-deploy-657bcbd7b-w2fqj                1/1     Running            0          15h
test-instance-ibm-es-rest-deploy-7dd6f57778-xp9pk                3/3     Running            0          15h
test-instance-ibm-es-ui-deploy-bfd7dfd96-qwn4s                   3/3     Running            0          15h
test-instance-ibm-es-zook-c4c0-0                                 1/1     Running            0          15h
test-instance-ibm-es-zook-c4c0-1                                 1/1     Running            0          15h
test-instance-ibm-es-zook-c4c0-2                                 1/1     Running            0          15h

helm:

global:
  image:
    repository: mycluster.icp:8500/event-streams
    pullSecret: regcred
    pullPolicy: IfNotPresent
    imageTags:
      kafkaTag: 2018-11-23-09.03.09-f51c694
      healthcheckTag: 2018-11-21-16.21.30-9947d87
      kafkaMetricsProxyTag: 2018-11-22-13.44.45-932c41b
      metricsReporterTag: 2018-11-15-16.03.55-fc56475
      zookeeperTag: 2018-11-15-16.04.27-97fcd55
      kafkaProxyTag: 2018-11-21-09.10.49-192cd69
      proxyTag: 2018-11-21-09.10.54-83bacb7
      uiTag: 2018-11-23-14.41.34-5551d4d
      codegenTag: 2018-11-21-11.58.59-4a844ff
      oauthTag: 2018-11-15-16.06.08-0e82f45
      roleMappingsTag: 2018-11-15-16.06.41-a193f91
      restTag: 2018-11-23-10.08.32-1d3a9a6
      elasticSearchTag: 2018-11-15-16.07.36-41f575c
      indexmgrTag: 2018-11-21-12.49.59-6879c17
      telemetryTag: 2018-11-15-16.08.19-17b74dc
      replicatorTag: 2018-11-15-16.50.56-c9a89c3
      accessControllerTag: 2018-11-23-11.54.42-58ce6ac
      kubectlTag: 2018-11-15-16.27.22-6a75737
      certGenTag: 2018-11-15-16.09.38-317444b
      redisTag: 2018-11-22-17.05.03-8dfe09e
      busyboxTag: 2018-11-15-16.10.31-12d2260
      alpineTag: 2018-11-21-15.56.28-ebba125
  fsGroupGid: null
  arch: amd64
telemetry:
  enabled: false
kafka:
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  metricsReporterResources:
    limits:
      memory: 1500Mi
    requests:
      memory: 1500Mi
  brokers: 3
  configMapName: ""
  interBrokerProtocolVersion: "2.0"
  logMessageFormatVersion: "2.0"
  heapOpts: -XX:+UseContainerSupport
persistence:
  enabled: true
  useDynamicProvisioning: true
  dataPVC:
    name: datadir
    storageClassName: "kafka-server"
    size: 4Gi
zookeeper:
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 750Mi
  persistence:
    enabled: true
    useDynamicProvisioning: true
  dataPVC:
    name: datadir
    storageClassName: "kafka-zookeeper"
    size: 2Gi
proxy:
  externalEndpoint: ""
tls:
  type: selfsigned
  key: null
  cert: null
  cacert: null
messageIndexing:
  messageIndexingEnabled: true
  resources:
    limits:
      memory: 4Gi
replicator:
  replicas: 0
  metricsReporterResources:
    limits:
      memory: 1500Mi
    requests:
      memory: 1500Mi
license: accepted

Log test-instance-ibm-es-kafka-sts-0
[2019-03-08 08:31:30,056] INFO Opening socket connection to server test-instance-ibm-es-zookeeper-fixed-ip-svc-0.event-streams.svc.cluster.local/10.0.122.38:2181 (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,056] ERROR [ZooKeeperClient] Auth failed. (kafka.zookeeper.ZooKeeperClient)
[2019-03-08 08:31:30,056] INFO Socket connection established to test-instance-ibm-es-zookeeper-fixed-ip-svc-0.event-streams.svc.cluster.local/10.0.122.38:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,057] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,812] WARN SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/jaas/event_streams_jaas.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,813] INFO Opening socket connection to server test-instance-ibm-es-zookeeper-fixed-ip-svc-1.event-streams.svc.cluster.local/10.0.68.237:2181 (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,813] ERROR [ZooKeeperClient] Auth failed. (kafka.zookeeper.ZooKeeperClient)
[2019-03-08 08:31:30,814] INFO Socket connection established to test-instance-ibm-es-zookeeper-fixed-ip-svc-1.event-streams.svc.cluster.local/10.0.68.237:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:30,815] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,659] WARN SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/jaas/event_streams_jaas.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,660] INFO Opening socket connection to server test-instance-ibm-es-zookeeper-fixed-ip-svc-2.event-streams.svc.cluster.local/10.0.203.71:2181 (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,660] ERROR [ZooKeeperClient] Auth failed. (kafka.zookeeper.ZooKeeperClient)
[2019-03-08 08:31:32,661] INFO Socket connection established to test-instance-ibm-es-zookeeper-fixed-ip-svc-2.event-streams.svc.cluster.local/10.0.203.71:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,661] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,678] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[2019-03-08 08:31:32,765] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2019-03-08 08:31:32,767] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
[2019-03-08 08:31:32,770] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[2019-03-08 08:31:32,777] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:230)
	at kafka.zookeeper.ZooKeeperClient$$Lambda$107.000000001D1E3870.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:226)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1588)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:348)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
[2019-03-08 08:31:32,781] INFO shutting down (kafka.server.KafkaServer)
[2019-03-08 08:31:32,784] WARN  (kafka.utils.CoreUtils$)
java.lang.NullPointerException
	at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:579)
	at kafka.server.KafkaServer$$Lambda$129.000000001D1E1DA0.apply$mcV$sp(Unknown Source)
	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:86)
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:579)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:329)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
[2019-03-08 08:31:32,792] INFO shut down completed (kafka.server.KafkaServer)
[2019-03-08 08:31:32,794] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2019-03-08 08:31:32,798] INFO shutting down (kafka.server.KafkaServer)

Log test-instance-ibm-es-elastic-sts-0
[2019-03-08T08:32:34,648][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [aggs-matrix-stats]
[2019-03-08T08:32:34,649][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [analysis-common]
[2019-03-08T08:32:34,649][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [ingest-common]
[2019-03-08T08:32:34,649][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-expression]
[2019-03-08T08:32:34,649][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-mustache]
[2019-03-08T08:32:34,649][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-painless]
[2019-03-08T08:32:34,650][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [mapper-extras]
[2019-03-08T08:32:34,650][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [parent-join]
[2019-03-08T08:32:34,650][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [percolator]
[2019-03-08T08:32:34,650][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [rank-eval]
[2019-03-08T08:32:34,651][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [reindex]
[2019-03-08T08:32:34,651][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [repository-url]
[2019-03-08T08:32:34,651][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [transport-netty4]
[2019-03-08T08:32:34,651][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [tribe]
[2019-03-08T08:32:34,652][INFO ][o.e.p.PluginsService     ] [node-0] no plugins loaded
--2019-03-08 08:32:35--  http://test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc:9200/
Resolving test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)... 10.1.30.126
Connecting to test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)|10.1.30.126|:9200... failed: Connection refused.
--2019-03-08 08:32:36--  http://test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc:9200/
Resolving test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)... 10.1.30.126
Connecting to test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)|10.1.30.126|:9200... failed: Connection refused.
--2019-03-08 08:32:37--  http://test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc:9200/
Resolving test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)... 10.1.30.126
Connecting to test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc (test-instance-ibm-es-elastic-sts-0.test-instance-ibm-es-elastic-svc)|10.1.30.126|:9200... failed: Connection refused.
[2019-03-08T08:32:37,331][INFO ][o.e.d.DiscoveryModule    ] [node-0] using discovery type [zen]
[2019-03-08T08:32:37,860][INFO ][o.e.n.Node               ] [node-0] initialized
[2019-03-08T08:32:37,860][INFO ][o.e.n.Node               ] [node-0] starting ...
[2019-03-08T08:32:38,017][INFO ][o.e.t.TransportService   ] [node-0] publish_address {10.1.30.126:9300}, bound_addresses {10.1.30.126:9300}
[2019-03-08T08:32:38,027][INFO ][o.e.b.BootstrapChecks    ] [node-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2019-03-08T08:32:38,036][INFO ][o.e.n.Node               ] [node-0] stopping ...
[2019-03-08T08:32:38,054][INFO ][o.e.n.Node               ] [node-0] stopped
[2019-03-08T08:32:38,054][INFO ][o.e.n.Node               ] [node-0] closing ...
[2019-03-08T08:32:38,068][INFO ][o.e.n.Node               ] [node-0] closed

Please assist.

**Comment by dalelane** [comment]
Thanks very much for getting in touch, and sorry that you're having trouble with this. 

There are two issues that I can see in here.

1) 
The Elastic Search pods aren't starting. The relevant error here in your comment is:

```
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

For message indexing capabilities (which are enabled by default), you need to set the vm.max_map_count property to at least 262144 on all IBM Cloud Private nodes in your cluster (not only the master node). There are instructions on how to do this at https://ibm.github.io/event-streams/installing/prerequisites/

Alternatively, you can disable message indexing for your Event Streams install, so that the Elastic Search pods aren't deployed.


2)
The Kafka pods are having problems connecting to ZooKeeper which is why they shut down. (The auth failure is not the issue here, that is always in the log at startup). I can't immediately tell the reason for this, but at first glance it looks like a networking/connectivity issue between the pods.

If you would be willing to collect additional logs, that would be helpful for investigating this further. I've attached a script for collecting this. Instructions for running it are at the top of the file. 
[get-logs.sh.txt](https://github.com/IBM/event-streams/files/2945145/get-logs.sh.txt)

If you could send us the zip that this script would produce, the additional info might help uncover the reason for connections not being allowed from the Kafka pods to the ZooKeeper pods.

**Comment by EmmaHumber** [comment]
Can I also check what OS you're running on and if SE Linux is enabled?

Thanks!

**Comment by jochen1234** [comment]
Thank you very much!

Problem 1: Starting the elastic server is solved!

Problem 2: Was my fault too. I f had some old data in the zookeeper volumes from previous installations. After removing this, all things worked fine.
