### ISSUE TITLE
 Schema Registry auto-schema registration id generation problem

### ISSUE THREAD

**Issue by ajborley** [IBM/event-streams#99]
## Issue Description

The Event Streams Schema Registry uses a hash function to generate a consistent ID for new schemas based on the subject name. It produces a 32-bit unsigned int.

The Java Confluent client expects an int
https://github.com/confluentinc/schema-registry/blob/a91a82f795cc5afd1d85545ce14af78d174a52b7/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/requests/RegisterSchemaResponse.java#L28

This means that for some subject names, the Java client throws an exception when trying to process the API response from the schema registry:

org.apache.kafka.common.errors.SerializationException Error serializing Avro message
Caused by: com.fasterxml.jackson.databind.JsonMappingException Numeric value (2257871337) out of range of int
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 17]
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 7] (through reference chain: io.confluent.kafka.schemaregistry.client.rest.entities.requests.RegisterSchemaResponse["id"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:188)

## Environment

* IBM Event Streams Version: 2019.4.2

**Comment by Steve-Dare** [comment]
Fixed by IBM internal issue 5774, closing.
